config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

 # get "files/index"
  resources :members
  root 'members#index'
  resources :transactions
  resources :budgets
  resources :events
  resources :shifts
  resources :attendances
  resources :files

  get 'admin', to: 'admin#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  put "sign_in" =>'attendances#sign_in'
end

app/views/admin/index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert" id="hideMeAfter5Seconds" style="position: fixed; right: 1rem;">
    <%= flash[:notice] %>
  </div>
<% end %>

<div class="d-flex flex-wrap align-items-center gap-4 mb-4">
  <h1 class="mb-0"> Admin Controls </h1>

  <%= link_to 'Reset Dues', url_for(:param => 'Reset Dues'), data: { confirm: 'Are you sure you want to set all member dues to Unpaid?' }, class: "btn btn-primary btn-new div-mobile" %>

  <%= link_to 'Reset Hours', url_for(:param => 'Reset Hours'), data: { confirm: 'Are you sure you want to reset current member hours to track from now?' }, class: "btn btn-primary btn-new div-mobile" %>

  <%= link_to 'Increase Grade', url_for(:param => 'Increase Grade'), data: { confirm: 'Are you sure you want to increase the grade level of all members?' }, class: "btn btn-primary btn-new div-mobile" %>
</div>

<div class="d-flex align-items-center gap-3 mb-2">
  <h1 style="margin: 0">Officers</h1>

  <%= link_to "New Officer", new_member_path(:admin => 'Create Officer'), class: "btn btn-primary btn-new" %>
</div>

<div class="table-ruby table-responsive mb-4"> <%#table-responsive shows white at bottom of table %>
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <!--NAME COLUMN-->
        <th style="width: 16rem">
          Name 
          <%if (@toggle == nil || @toggle != 1) &&  @toggle != 0%>
            <%= link_to admin_path+"?sort=Last_Name", :class => 'name_links' do %>
              <%= image_tag "sort.svg", style: 'height:1rem; width:1rem;' %>
            <% end %>
          <%elsif @toggle == 0%>
            <%= link_to admin_path+"?sort=Last_Name_Desc", :class => 'name_links' do %>
              <%= image_tag "sort.svg", style: 'height:1rem; width:1rem;' %>
            <% end %>
          <%end%>
        </th>

        <!--ROLE COLUMN-->
        <th>
          Role 
          <%if (@toggle == nil || @toggle != 3) &&  @toggle != 2%>
            <%= link_to admin_path+"?sort=Role", :class => 'name_links' do %>
              <%= image_tag "sort.svg", style: 'height:1rem; width:1rem;' %>
            <% end %>
          <%elsif @toggle == 2%>
            <%= link_to admin_path+"?sort=Role_Desc", :class => 'name_links' do %>
              <%= image_tag "sort.svg", style: 'height:1rem; width:1rem;' %>
            <% end %>
          <%end%>
        </th>

        <!--EMAIL COLUMN-->
        <th style="width: 18rem">
          Email 
          <%if (@toggle == nil || @toggle != 5) &&  @toggle != 4%>
            <%= link_to admin_path+"?sort=Email", :class => 'name_links' do %>
              <%= image_tag "sort.svg", style: 'height:1rem; width:1rem;' %>
            <% end %>
          <%elsif @toggle == 4%>
            <%= link_to admin_path+"?sort=Email_Desc", :class => 'name_links' do %>
              <%= image_tag "sort.svg", style: 'height:1rem; width:1rem;' %>
            <% end %>
          <%end%>
        </th>


        <th>Fall Dues</th>
        <th>Spring Dues</th>

        <!--SHIRT SIZE COLUMN-->
        <th>
          Shirt Size 
          <%if (@toggle == nil || @toggle != 7) &&  @toggle != 6%>
            <%= link_to admin_path+"?sort=Shirt", :class => 'name_links' do %>
              <%= image_tag "sort.svg", style: 'height:1rem; width:1rem;' %>
            <% end %>
          <%elsif @toggle == 6%>
            <%= link_to admin_path+"?sort=Shirt_Desc", :class => 'name_links' do %>
              <%= image_tag "sort.svg", style: 'height:1rem; width:1rem;' %>
            <% end %>
          <%end%>
        </th>

        <th>
          Year 
          <%if (@toggle == nil || @toggle != 9) &&  @toggle != 8%>
            <%= link_to admin_path+"?sort=Year", :class => 'name_links' do %>
              <%= image_tag "sort.svg", style: 'height:1rem; width:1rem;' %>
            <% end %>
          <%elsif @toggle == 8%>
            <%= link_to admin_path+"?sort=Year_Desc", :class => 'name_links' do %>
              <%= image_tag "sort.svg", style: 'height:1rem; width:1rem;' %>
            <% end %>
          <%end%>
        </th>

        <th>
          Total Hours 
          <%if (@toggle == nil || @toggle != 15) &&  @toggle != 10%>
            <%= link_to admin_path+"?sort=Hours", :class => 'name_links' do %>
              <%= image_tag "sort.svg", style: 'height:1rem; width:1rem;' %>
            <% end %>
          <%elsif @toggle == 10%>
            <%= link_to admin_path+"?sort=Hours_Desc", :class => 'name_links' do %>
              <%= image_tag "sort.svg", style: 'height:1rem; width:1rem;' %>
            <% end %>
          <%end%>
        </th>
        <th class="actions">Action</th>
      </tr>
    </thead>
    
    <tbody>
    <%#delete where not statement to see seed values %>
      <%  @members.each do |member| %>
          <% if member.Role > 0%>
            <tr>
              <td><%= link_to member.First_Name + " " + member.Last_Name, member, :class => 'name_links', :style => 'color: black'; %></td>
              
              <%if member.Role == 0 %>
                <td>Member</td>
              <%elsif member.Role == 1 %>
                <td>Technology Chair</td>
              <%elsif member.Role == 2%>
                <td>Social Chair</td>
              <%elsif member.Role == 3%>
                <td>Secretary</td>
              <%elsif member.Role == 4 %>
                <td>VP</td>
              <%elsif member.Role == 5%>
                <td>Treasurer</td>
              <%elsif member.Role == 6%>
                <td>President</td>
              <%else%>
                <td>Member</td>
              <%end%>
              
              <td><%= member.Email %></td>

              <%if member.Fall_Dues == true %>
                <td>Paid</td>
              <%else%>
                <td>Unpaid</td>
              <%end%>

              <%if member.Spring_Dues == true %>
                <td>Paid</td>
              <%else%>
                <td>Unpaid</td>
              <%end%>

              <td><%= member.Shirt_Size %></td>

              <%if member.year == 1 %>
                <td>Freshman</td>
              <%elsif member.year == 2%>
                <td>Sophmore</td>
              <%elsif member.year == 3%>
                <td>Junior</td>
              <%elsif member.year == 4%>
                <td>Senior</td>
              <%elsif member.year == 5%>
                <td>Graduate</td>
              <%else%>
                <td>Alumni</td>
              <%end%>

              <td><%= Attendance.where(Member_id: member.id).where('"created_at" > ?', Budget.first.Date).sum(:Hours) %></td>

              <td class="text-center">
                <%= link_to member_path(member), :class => 'name_links' do %>
                  <%= image_tag "inspect3.svg", style: 'height:1rem; width:1rem;' %>
                <% end %>
                &nbsp;
                <%= link_to edit_member_path(member), :class => 'name_links' do %>
                  <%= image_tag "pencil-square.svg", style: 'height:1rem; width:1rem;' %>
                <% end %>
                &nbsp;
                <%= link_to member, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'name_links' do %>
                  <%= image_tag "trash.svg", style: 'height:1rem; width:1rem;' %>
                <% end %>
              </td>
            </tr>
          <%end%>
      <% end %>
    </tbody>
  </table>
</div>

<h1 class="mb-2">Deployment and Support Plan</h1>