config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

 # get "files/index"
  resources :members
  root 'members#index'
  resources :transactions
  resources :budgets
  resources :events
  resources :shifts
  resources :attendances
  resources :files

  get 'admin', to: 'admin#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  put "sign_in" =>'attendances#sign_in'
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :Shifts
    has_many :Attendance, through: :Shifts

#Validations for member form input fields
=begin
New Event
	type default 0
	date defaults to todays date
	name must be filled in
	start time must be input (restrict to valid times)
	does NOT need end time
=end
    validates :Type, presence: true
    validates :Name, presence: true
    validates :Date, presence: true
    validates :Start, presence: true

    validates_time :End, on_or_after: :Start, before_message: "End time must be on or after the start time"

    def to_s
        title
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  
  before_action :authenticate_user!
  before_action :check_officer_privelege
  before_action :generate_qr_attendance
  before_action :generate_qr_shifts
  
  # GET /events or /events.json
  def index
    @events = Event.all
  end

  def names
    @names = Member.all
  end

  # GET /events/1 or /events/1.json
  def show
    @EventShifts = Shift.where(Event_id: params[:id])
    @EventAttendances = Attendance.joins(:Shift).where(Shift: {Event_id: params[:id]})
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created" }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated" }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully deleted" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:Type, :Date, :Name, :Start, :End)
    end

    def generate_qr_attendance
      qrcode_attendance = RQRCode::QRCode.new(request.base_url + "/attendances/new?signup=1" )
      png = qrcode_attendance.as_png(
          bit_depth: 1,
          border_modules: 4,
          color_mode: ChunkyPNG::COLOR_GRAYSCALE,
          color: "black",
          file: nil,
          fill: "white",
          module_px_size: 6,
          resize_exactly_to: false,
          resize_gte_to: false,
          size: 120
      )
      @png = png.to_s
    end

    def generate_qr_shifts
      qrcode_shift = RQRCode::QRCode.new(request.base_url + "/attendances" )
      png = qrcode_shift.as_png(
          bit_depth: 1,
          border_modules: 4,
          color_mode: ChunkyPNG::COLOR_GRAYSCALE,
          color: "black",
          file: nil,
          fill: "white",
          module_px_size: 6,
          resize_exactly_to: false,
          resize_gte_to: false,
          size: 120
      )
      @png2 = png.to_s   
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="form">
  <h1 class="form-title"><%= heading %></h1>

  <%= bootstrap_form_with(model: event) do |form| %>
    <% if event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

        <ul>
          <% event.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="col-md-12">
        <%= form.text_field :Name %>
      </div>

      <%# drop down menu to chose between a meeting and volunteer event %>
      <div class="col-md-6">
        <%= form.select :Type, options_for_select([['Club Meeting', 0], ['Volunteer Event', 1]]) %>
      </div>

      <div class="col-md-6">
        <%= form.date_field :Date %>
      </div>

      <div class="col-md-6">
        <%= form.label :Start, "Start Time", class: "form-label" %>
        <%= form.time_select :Start, default: {hour: 12, min: 0}, :minute_step => 5, :twelve_hour => true, :ampm => true, hide_label: true %>
      </div>

      <div class="col-md-6">
        <%= form.label :End, "End Time", class: "form-label" %>
        <%= form.time_select :End, default: {hour: 12, min: 0}, :minute_step => 5, :twelve_hour => true, :ampm => true, hide_label: true %>
      </div>

      <div>
        <%= form.submit class: "btn btn-primary btn-form" %>
      </div>
        
    </div>
  <% end %>
  <%= link_to 'Back', :back %>
</div>

app/views/events/attendance_form.html.erb
<%= form_with(model: event) do |form| %>
<%end%>

app/views/events/edit.html.erb
<%= render 'form', event: @event, heading: "Edit Event" %>

app/views/events/index.html.erb
<%= stylesheet_link_tag 'events' %>
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert" id="hideMeAfter5Seconds" style="position: fixed; right: 1rem;">
    <%= flash[:notice] %>
  </div>
<% end %>

<div class="d-flex align-items-center gap-3 mb-4">
  <h1 style="margin: 0">Events</h1>

  <%= link_to 'New Event', new_event_path, :class => 'btn btn-primary btn-new' %>
</div>

<h1 class="mb-2"> Upcoming </h1>
<div class="table-ruby table-responsive mb-4"> <%#table-responsive shows white at bottom of table %>
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th style="width: 20.25rem">Name</th>
        <th style="width: 20.25rem">Type</th>
        <th style="width: 11.75rem">Date</th>
        <th style="width: 11.75rem">Start Time</th>
        <th style="width: 11.75rem">End Time</th>
        <th class="actions">Action</th>
      </tr>
    </thead>
    <tbody>
      <%# .. and ... is <= and < %>
      <%# @events.where.not(Date: ...Date.current).each do |event| %>
      <% @events.each do |event| %>
        <% if event.Date < Date.current %>
      
        <% else %>
          <tr>
            <td><%= link_to event.Name, event, :class => 'name_links', :style => 'color: black'; %></td>
            <%if event.Type == 0 %>
              <td>Club Meeting</td>
            <%else%>
              <td>Volunteer Event</td>
            <%end%>
            <td><%= event.Date.strftime("%m/%d/%Y") %></td>
            <td><%= event.Start.strftime("%I:%M %p") %></td>
            <td><%= event.End.strftime("%I:%M %p") %></td>
            <td class="text-center">
              <%= link_to event_path(event), :class => 'name_links' do %>
                <%= image_tag "inspect3.svg", style: 'height:1rem; width:1rem;' %>
              <% end %>
              &nbsp;
              <%= link_to edit_event_path(event), :class => 'name_links' do %>
                <%= image_tag "pencil-square.svg", style: 'height:1rem; width:1rem;' %>
              <% end %>
              &nbsp;
              <%= link_to event, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'name_links' do %>
                <%= image_tag "trash.svg", style: 'height:1rem; width:1rem;' %>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<h1 class="mb-2"> Previous </h1>
<div class="table-ruby table-responsive mb-4"> <%#table-responsive shows white at bottom of table %>
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th style="width: 20.25rem">Name</th>
        <th style="width: 20.25rem">Type</th>
        <th style="width: 11.75rem">Date</th>
        <th style="width: 11.75rem">Start Time</th>
        <th style="width: 11.75rem">End Time</th>
        <th class="actions">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @events.each do |event| %>
        <% if event.Date >= Date.current %>
      
        <% else %>
          <tr>
            <td><%= link_to event.Name, event, :class => 'name_links', :style => 'color: black'; %></td>
            <%if event.Type == 0 %>
              <td>Club Meeting</td>
            <%else%>
              <td>Volunteer Event</td>
            <%end%>
            <td><%= event.Date.strftime("%m/%d/%Y") %></td>
            <td><%= event.Start.strftime("%I:%M %p") %></td>
            <td><%= event.End.strftime("%I:%M %p") %></td>
            <td class="text-center">
              <%= link_to event_path(event), :class => 'name_links' do %>
                <%= image_tag "inspect3.svg", style: 'height:1rem; width:1rem;' %>
              <% end %>
              &nbsp;
              <%= link_to edit_event_path(event), :class => 'name_links' do %>
                <%= image_tag "pencil-square.svg", style: 'height:1rem; width:1rem;' %>
              <% end %>
              &nbsp;
              <%= link_to event, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'name_links' do %>
                <%= image_tag "trash.svg", style: 'height:1rem; width:1rem;' %>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/events/new.html.erb
<%= render 'form', event: @event, heading: "New Event" %>

app/views/events/show.html.erb
<%= stylesheet_link_tag 'events' %>
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert" id="hideMeAfter5Seconds" style="position: fixed; right: 1rem;">
    <%= flash[:notice] %>
  </div>
<% end %>

<!--EVENT INFO-->
<div class="show-event mb-4">
  <div class="d-flex flex-wrap">
    <div class="flex-grow-1">
      <p>
        <strong>Name:</strong>
        <%= @event.Name %>
      </p>

      <p>
        <strong>Type:</strong>
          <%if @event.Type == 0 %>
            Club Meeting
          <%else%>
            Volunteer Event
          <%end%>
      </p>

      <p>
        <strong>Date:</strong>
        <%= @event.Date.strftime("%m/%d/%Y") %>
      </p>

      <p>
        <strong>Start Time:</strong>
        <%= @event.Start.strftime("%I:%M %p") %>
      </p>

      <p class="mb-0">
        <strong>End Time:</strong>
        <%= @event.End.strftime("%I:%M %p") %>
      </p>
    </div>

    <div class="d-flex flex-column show-qr">
      <p class="mb-0 text-center"><strong> Sign Up </strong></p>
      <%= image_tag "data:image/png;base64,#{Base64.strict_encode64(@png)}" %>
      <%= link_to 'Download PNG', "data:image/png;base64,#{Base64.strict_encode64(@png)}", download: "qr", :class => 'btn btn-primary btn-new div-mobile' %>
    </div>

    <div class="d-flex flex-column show-qr">
      <p class="mb-0 text-center"><strong> Sign In </strong></p>
      <%= image_tag "data:image/png;base64,#{Base64.strict_encode64(@png2)}" %>
      <%= link_to 'Download PNG', "data:image/png;base64,#{Base64.strict_encode64(@png2)}", download: "qr", :class => 'btn btn-primary btn-new div-mobile' %>
    </div>
  </div>
</div>

<!--SHIFTS-->
<div class="d-flex align-items-center gap-3 mb-2">
  <h1 style="margin: 0">Shifts</h1>

    <%= link_to 'New Shift', new_shift_path(:event_id => @event.id), :class => 'btn btn-primary btn-new' %>
  </div>

<!--SHIFTS TABLE-->
<div class="table-ruby table-responsive mb-4"> 
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th>Start Time</th>
        <th>End Time</th>
        <th>Max Volunteers</th>
        <th>Remaining Spots</th>
        <th style="width: 5.25rem;">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @EventShifts.each do |shift| %>
        <tr>
          <td><%= shift.Start.strftime("%I:%M %p") %></td>
          <td><%= shift.End.strftime("%I:%M %p") %></td>
          <td><%= shift.Shift_Cap %></td>
          <td><%= shift.Shift_Cap - Attendance.where(Shift_id: shift.id).size %></td>
          <td>
            <%= link_to edit_shift_path(shift), :class => 'name_links' do %>
              <%= image_tag "pencil-square.svg", style: 'height:1rem; width:1rem;' %>
            <% end %>
            &nbsp;
            <%= link_to shift, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'name_links' do %>
              <%= image_tag "trash.svg", style: 'height:1rem; width:1rem;' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="row">
  <!--Column 1/2-->
  <!--SIGN UPS-->
  <% if @event.Date > Date.current %>
    <div class="col mb-4">
      <div class="d-flex align-items-center gap-3 mb-2">
        <h1 style="margin: 0">Sign Ups</h1>
      </div>

      <!--SIGN UPS TABLE-->
      <div class="table-ruby table-responsive"> <%#table-responsive shows white at bottom of table %>
        <table class="table table-hover table-striped">
          <thead>
            <tr>
              <th>Member</th>
              <th>Start Time</th>
              <th>End Time</th>
              <th class="actions">Action</th>
            </tr>
          </thead>
          <tbody>
            <% @EventAttendances.each do |att| %>
              <tr>
                <%if att.Hours == 0 %>
                  <td><%=  Member.find(att.Member_id).First_Name%> <%= Member.find(att.Member_id).Last_Name %></td>
                  <td><%=  Shift.find(att.Shift_id).Start.strftime("%I:%M %p") %></td>
                  <td><%=  Shift.find(att.Shift_id).End.strftime("%I:%M %p") %></td>
                  <td class="text-center">
                    <%= link_to edit_attendance_path(att.id), :class => 'name_links' do %>
                      <%= image_tag "pencil-square.svg", style: 'height:1rem; width:1rem;' %>
                    <% end %>
                    &nbsp;
                    <%= link_to attendance_path(att.id), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'name_links' do %>
                      <%= image_tag "trash.svg", style: 'height:1rem; width:1rem;' %>
                    <% end %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <%end%>

  <div class="col mb-4">
    <!--Column 2/2-->
    <!--ATTENDACES-->
    <div class="d-flex align-items-center gap-3 mb-2">
      <h1 style="margin: 0">Attendaces</h1>
      <%= link_to 'New Attendance', new_attendance_path(:event_id => @event.id), :class => 'btn btn-primary btn-new' %>
    </div>

    <!--ATTENDACES TABLE-->
    <div class="table-ruby table-responsive"> <%#table-responsive shows white at bottom of table %>
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>Member</th>
            <th>Hours</th>
            <th class="actions">Action</th>
          </tr>
        </thead>

        <tbody>
          <tbody>
            <% @EventAttendances.each do |att| %>
              <tr>
                <%if att.Hours > 0 %>
                  <td><%=  Member.find(att.Member_id).First_Name%> <%= Member.find(att.Member_id).Last_Name %></td>
                  <td><%= att.Hours %></td>
                  <td class="text-center">
                    <%= link_to edit_attendance_path(att.id), :class => 'name_links' do %>
                      <%= image_tag "pencil-square.svg", style: 'height:1rem; width:1rem;' %>
                    <% end %>
                    &nbsp;
                    <%= link_to attendance_path(att.id), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'name_links' do %>
                      <%= image_tag "trash.svg", style: 'height:1rem; width:1rem;' %>
                    <% end %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
      </table>
    </div>
  </div>
</div>

<!--PAGE PATHS-->
<%= link_to 'Back', events_path %>