config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

 # get "files/index"
  resources :members
  root 'members#index'
  resources :transactions
  resources :budgets
  resources :events
  resources :shifts
  resources :attendances
  resources :files

  get 'admin', to: 'admin#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  put "sign_in" =>'attendances#sign_in'
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :check_officer_privelege
  before_action :check_transaction_privelege

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.all.order(:Date).reverse_order
    # @budgets = Budget.all
  end

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction_type = params[:ttype]
    @transaction = Transaction.new(Date: Date.current)
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    @t_type = params[:commit]
    create_params = transaction_params
    notice_msg = "Deposit was successfully created"

    if @t_type == 'Withdraw'
      create_params[:Amount] = -1 * create_params[:Amount].to_i
      puts params[:Amount]
      notice_msg = "Withdraw was successfully created"
    end
      
    @transaction = Transaction.new(create_params)
    @transaction.Total = Transaction.sum(:Amount) + @transaction.Amount

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transactions_url, notice: notice_msg }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    beforeUpdate = @transaction.Amount
    respond_to do |format|
      if @transaction.update(transaction_params)
        @updateBudget = @transaction.Budget.update(Total_amount: @transaction.Budget.Total_amount.to_f + transaction_params[:Amount].to_f - beforeUpdate.to_f ) 
        format.html { redirect_to transactions_url, notice: "Transaction was successfully updated" }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    # @transaction.Budget.update(Total_amount: @transaction.Budget.Total_amount.to_f - @transaction.Amount)
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "Transaction was successfully deleted" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:Budget_id, :Purpose, :Amount, :Date, :Officer, :transaction_type, :Total)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<div class="form">
  <h1 class="form-title"><%= heading %></h1>

  <%= bootstrap_form_with(model: transaction) do |form| %>
    <% if transaction.errors.any? %>
      <%= form.alert_message "Please fix the errors below", error_summary: false %>
    <% end %>

    <div class="row">
        <div class="col-md-12" style="display:none">
          <%= form.label :Budget_id %>
          <%= form.select :Budget_id, selected: 1 , id: "id of event" %>
        </div>    

      <div class="col-md-12">
        <%= form.text_field :Purpose %>
      </div>

      <div class="col-md-6">
        <%= form.number_field :Amount, :step=>"0.01", prepend: "$" %>
      </div>

      <div class="col-md-6">
        <%= form.date_field :Date %>
      </div>

      <div class="col-md-12">
        <%= form.text_field :Officer %>
      </div>

      <div>
        <%= form.submit class: "btn btn-primary btn-form", value: @transaction_type %> 
      </div>
        
    </div>
  <% end %>

  <%= link_to 'Back', transactions_path %>
</div>

app/views/transactions/edit.html.erb
<%= render 'form', transaction: @transaction, heading: "Edit Transaction" %>

app/views/transactions/index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert" id="hideMeAfter5Seconds" style="position: fixed; right: 1rem;">
    <%= flash[:notice] %>
  </div>
<% end %>

<div class="d-flex align-items-center gap-3 mb-2">
  <h1 style="margin: 0">Balance </h1>
    <h1 style="margin: 0; font-weight: 300;"><%= number_to_currency(Transaction.sum(:Amount)) %></h1>
</div>

<br>

<div class="row m-0 w-100 mb-4">
  <div class="col-sm-8 p-0 mb-2">
    <%= line_chart Transaction.pluck(:Date, :Total), refresh: 5, title: "Balance vs Time", xtitle: "Date", ytitle: "$", curve: false, colors: ["#FF0000", "#FFFFFF"], height: "20rem" %>
  </div>
  <div class="col p-0">
    <%= pie_chart Transaction.where('"Amount" < 0').group(:Purpose).sum(:Amount), refresh: 5, title: "Expenditures", colors: ["#FF0000", "#d3d3d3", "#a9a9a9"], height: "20rem" %>
  </div>
</div>

<br>

<div class="d-flex align-items-center gap-3 mb-2">
  <h1 style="margin: 0">Transactions</h1>

  <%= link_to 'Deposit', new_transaction_path(:ttype => 'Deposit'), :class => 'btn btn-primary btn-new' %>
  <%= link_to 'Withdraw', new_transaction_path(:ttype => 'Withdraw'), :class => 'btn btn-primary btn-new' %>
</div>

<div class="table-ruby table-responsive mb-4">
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th>Purpose</th>
        <th>Amount</th>
        <th>Date</th>
        <th>Officer</th>
        <th class="actions">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @transactions.each do |transaction| %>
        <tr>
          <td><%= transaction.Purpose %></td>
          <td><%= number_to_currency(transaction.Amount) %></td>
          <td><%= transaction.Date.strftime("%m/%d/%Y") %></td>
          <td><%= transaction.Officer %></td>
          <td class="text-center">
            <%= link_to edit_transaction_path(transaction), :class => 'name_links' do %>
              <%= image_tag "pencil-square.svg", style: 'height:1rem; width:1rem;' %>
            <% end %>
            &nbsp;
            <%= link_to transaction, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'name_links' do %>
              <%= image_tag "trash.svg", style: 'height:1rem; width:1rem;' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/transactions/new.html.erb
<%= render 'form', transaction: @transaction, heading: "New Transaction" %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.Amount %>
</p>

<p>
  <strong>Date:</strong>
  <%= @transaction.Date %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>